version: '2'

services:
    php:
        build: docker/php7
        links:
            - bigchaindb
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            -  ~/cache/composer/:/root/cache/composer
        command: php bin/console server:run 0.0.0.0:80 --env=dev
    rethinkdb:
        image: rethinkdb
        ports:
            - 58080:8080
            - 28015
        volumes:
            - ./docker/rethink_data:/data

    bigchaindb:
        build: docker/bigchaindb
        ports:
            - 9984:9984
            - 8080:8082
        volumes:
            - ./data/bigchain_data:/root/.bigchain_data
        links:
            - rethinkdb
        environment:
            BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
            BIGCHAINDB_DATABASE_HOST: rethinkdb
            BIGCHAINDB_CONFIG_PATH: /root/.bigchaindb