version: '2'

services:
    web:
        image: ntboes/golang-gin
        command: gin
        links:
            - bigchaindb
        ports:
            - 3000:80
        volumes:
            - ./app:/go/src/app
    rethinkdb:
        image: rethinkdb
        ports:
            - 58080:8080
            - 28015
        volumes:
            - ./docker/rethink_data:/data

    bigchaindb:
        build: docker/bigchaindb
        ports:
            - 9984:9984
            - 8080:8082
        volumes:
            - ./data/bigchain_data:/root/.bigchain_data
        links:
            - rethinkdb
        environment:
            BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
            BIGCHAINDB_DATABASE_HOST: rethinkdb
            BIGCHAINDB_CONFIG_PATH: /root/.bigchaindb